### ISSUE TITLE
Cannot connect to room. 

### ISSUE THREAD

**Issue by mayur-bhandari** [DimitrisTzimikas/RCTWebRTCDemo2#3]
I coned this repository and followed the steps. Everything is working but when i click on enter room it just says connecting and nothing happens. Please Help

**Comment by DimitrisTzimikas** [comment]
Did you use the ngrok link to connect to server? It sounds like you cannot connect to the server.

**Comment by PrashantRana95** [comment]
I used same as mentioned but when i opened in react native, it only shows Initializing.

**Comment by DimitrisTzimikas** [comment]
You run the server at the same time right?

**Comment by PrashantRana95** [comment]
Yeah i ran the server, ngrok and application but it got stuck on the Connecting then, not moving forward 
Also sometimes got stuck in Initializing, yeah i ran the server and ngrok at the same time
to.emit("exchange", data);
       ^

TypeError: Cannot read property 'emit' of undefined
    at Socket.socket.on.data 
    at Socket.emit (events.js:189:13)
    at 
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by mswubz** [comment]
so I updated the getLocalStream function to:

```
const getLocalStream = () => {
  let isFront = true;

  mediaDevices.enumerateDevices().then(sourceInfos => {
    console.log(sourceInfos);
    let videoSourceId;
    for (let i = 0; i < sourceInfos.length; i++) {
      const sourceInfo = sourceInfos[i];
      if(sourceInfo.kind == "videoinput" && sourceInfo.facing == (isFront ? "front" : "environment")) {
        videoSourceId = sourceInfo.deviceId;
      }
    }
    mediaDevices.getUserMedia({
      audio: true,
      video: {
        mandatory: {
          minWidth: 500, // Provide your own width, height and frame rate here
          minHeight: 300,
          minFrameRate: 30
        },
        facingMode: (isFront ? "user" : "environment"),
        optional: (videoSourceId ? [{sourceId: videoSourceId}] : [])
      }
    })
    .then(stream => {
      // Got stream!
      localStream = stream;

      appClass.setState({
        streamURL: stream.toURL(),
        status: 'ready',
        info: 'Welcome to WebRTC demo',
      });

      console.log('appClass.setState done.')
    })
    .catch(error => {
      // Log error
    });
  });
};
```
after this change I was able to enter a room

**Comment by DimitrisTzimikas** [comment]
@jnragu I've recently run it and worked. Can you highlight the changes that you made?

**Comment by mswubz** [comment]
@DimitrisTzimikas I changed everything within your getLocalStream function after let isFront = true; 

Recently the react-native-webrtc put getUserMedia within mediaDevices 

Also, before the updates I made, I could not switch the camera facing mode (tested on iOS)
